pluginVersion=1.4.19
pluginSinceBuild=261
runIdeVersion=2026.1.3

org.jetbrains.intellij.platform.selfUpdateCheck=false
org.jetbrains.intellij.platform.useCacheRedirector=true

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.configuration-cache=true
org.gradle.warning.mode=all
