pluginVersion=1.4.23
pluginSinceBuild=262
runIdeVersion=2026.2

org.jetbrains.intellij.platform.intellijPlatformIdesCacheEnabled=true
kotlin.stdlib.default.dependency=false

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.warning.mode=all
kotlin.daemon.jvmargs=-Xmx2048m
