name: Build

on:
  push:
    branches: [dev]
    tags: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

concurrency:
  group: build-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: jetbrains
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./scripts/build.sh

      - name: Verify Plugin
        run: ./scripts/verify.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: xmake-idea.zip
          path: ./build/distributions/xmake-idea.zip
          archive: false
